name: Build-Python-exe

on:
  schedule:
    - cron: "50 4 * * 1"
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - run: choco upgrade python -y
      - run: python --version
      - run: sh ./installResources.sh
      - run: pyinstaller.exe --onefile program.py
      - uses: actions/upload-artifact@v3
        with:
          name: program
          path: dist/program.exe
